
spring:
  datasource:
    url: jdbc:postgresql://localhost/sales_report?serverTimezone=UTC
    username: postgres
    password: ${DB_PASSWORD}
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    deserialization:
      fail_on_unknown_properties: true
      fail_on_ignored_properties: true
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
