CREATE TABLE product (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL,
    price DECIMAL(19, 2) NOT NULL,
    sku VARCHAR(10) NOT NULL UNIQUE,
    creation_date TIMESTAMP NOT NULL,
    update_date TIMESTAMP NOT NULL
);